**Univariate Feature Selection**

In [39]:
# out of 8 features of dataset which one is most important in predicting class?
# Feature Extraction with Univariate Statistical Tests (Chi-squared for classification)
from pandas import read_csv
import pandas as pd
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest # for univariate selection
from sklearn.feature_selection import chi2

In [40]:
# load data, Patient's details taken, Identify which variable is most important in identifying whether patient has dibetes or not
filename = '/content/pima-indians-diabetes.data.csv'
# In actual dataset no column names so give col names, Class - Y variable
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv(filename, names=names)
array = dataframe.values
dataframe.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [41]:
dataframe.shape

(768, 9)

In [42]:
X = array[:,0:8]
Y = array[:,8] # separate them in X and Y

# feature extraction
test = SelectKBest(score_func=chi2, k=5) # get top 5 features, K should be less than or equal to total no. of features
fit = test.fit(X, Y)
# summarize scores
set_printoptions(precision=4)
print(fit.scores_) # will get chi squares for each feature
#For regression: f_regression, mutual_info_regression
#For classification: chi2, f_classif, mutual_info_classif
# for feature 'test': chi square value is 2175.5653, so this is most imp feature, then plas,pedi,....

[ 111.5197 1411.887    17.6054   53.108  2175.5653  127.6693    5.3927
  181.3037]


In [43]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [ ]:
#features = fit.transform(X)
#features.shape

In [44]:
# store chi square values in a dataframe
x=pd.DataFrame(fit.scores_).T # .T will transpose list into dataframe


In [ ]:
x # column names are not displayed... only index is visible.

In [ ]:
x.columns=names[:8]
x
# As per chi square test, test is most important feature, Next..plas, age, mass, preg

In [27]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [ ]:
# Sort chi square values in ascending or descending order
sorted_x = x.sort_values(by = 0, ascending=False, axis = 1)
sorted_x

In [ ]:
dataframe

# Feature Scaling (standardization, Normalization etc.)

In [ ]:
# https://www.analyticsvidhya.com/blog/2021/05/feature-scaling-techniques-in-python-a-complete-guide/
# https://www.analyticsvidhya.com/blog/2020/07/types-of-feature-transformation-and-scaling/
# https://medium.datadriveninvestor.com/feature-scaling-in-data-science-5b1e82492727
# https://www.kaggle.com/code/aimack/complete-guide-to-feature-scaling

**Recursive Feature Elimination**

In [49]:
# Feature Extraction with RFE
from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
# load data
filename = '/content/pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv(filename, names=names)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]
# feature extraction
model = LogisticRegression(max_iter=400)# to find out coefficients of logistic regression, for that it need to iterate
# inside logistic regression optimization algorithm is there. Using that, coefficients will be estimated.
# For that it has to iterate multiple times. Default value is 100.
rfe = RFE(model)# see best features
fit = rfe.fit(X, Y)

In [50]:
#Num Features: 4 top features are available
fit.n_features_

4

In [52]:
#Selected Features:
fit.support_

array([ True,  True, False, False, False,  True,  True, False])

In [53]:
names # print column names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [54]:
# Feature Ranking:
fit.ranking_

array([1, 1, 3, 5, 4, 1, 1, 2])

In [55]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

#### Feature Importance using Decision Tree

In [56]:
# Feature Importance with Extra Trees Classifier
from pandas import read_csv
from sklearn.tree import  DecisionTreeClassifier
# load data
filename = '/content/pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv(filename, names=names)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]
# feature extraction
model = DecisionTreeClassifier()
model.fit(X, Y)
print(model.feature_importances_) # feature importance score

[0.0637 0.3115 0.0981 0.0181 0.0334 0.2226 0.1303 0.1222]


In [57]:
sorted_list=model.feature_importances_
print('Feature importance=',sorted_list)#Before sorting
sorted_list.sort()
print('Sorted Feature importance=',sorted_list)#After sorting

Feature importance= [0.0637 0.3115 0.0981 0.0181 0.0334 0.2226 0.1303 0.1222]
Sorted Feature importance= [0.0181 0.0334 0.0637 0.0981 0.1222 0.1303 0.2226 0.3115]


In [58]:
names # plas is most imp feature, then mass,age,pedi
# find common amongst all methods

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']